---
title: "RobinSingleCellVignette"
author: "Valeria Policastro"
date: "26/11/2021"
output: 
    html_document:
        code_folding: hide
        toc: true
        toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
### SET GENERAL OPTIONS FOR ALL CODE CHUNKS!
knitr::opts_chunk$set(echo = TRUE, message=FALSE, cache=TRUE, warning=FALSE)
```

# Single cell RNAseq Analysis

## Package loading 
```{r}

library(dplyr)
library(Seurat)
library(patchwork)
library(mclust)

```

## Reading data 
```{r}
tabData <- readRDS("Subsemple1percentemptyDroplets_doublet_filtered_tabulamuris_mtx.rds")

SingleCellData <- CreateSeuratObject(counts = tabData, project = "singleCell", min.cells = round(dim(tabData)[2]*5/100), min.features = 0)
SingleCellData 
```

## Data normalization
```{r}

SingleCellData <- NormalizeData(SingleCellData, normalization.method = "LogNormalize", scale.factor = 10000)

SingleCellData[["RNA"]]@data[1:5,1:5]



```


## Feature selection
```{r}

SingleCellData <- FindVariableFeatures(object = SingleCellData, selection.method="vst", nfeatures = 2000)

```


## Scale the data
```{r}
SingleCellData <- ScaleData(SingleCellData, do.center = TRUE, do.scale = TRUE)
SingleCellData[["RNA"]]@scale.data[1:5,1:5]


```

## Linear dimension reduction
```{r}
SingleCellData <- RunPCA(SingleCellData, features = VariableFeatures(object = SingleCellData))

```


## Graph construction
```{r}

SingleCellData <- FindNeighbors(SingleCellData, dims = 1:50) 

#SingleCellData@graphs$RNA_snn # Adjacency matrix
```


#How to use Robin

## Reading Graph
```{r}
library(robin)

AdjSNN <- SingleCellData@graphs$RNA_snn
graphSingleCell <- graph_from_adjacency_matrix(AdjSNN,mode="directed",weighted = TRUE,add.colnames = "NA",diag=FALSE)
edge <- as_edgelist(graphSingleCell)
graph <- igraph::graph_from_edgelist(edge, directed=FALSE)
graph <- igraph::simplify(graph)
graph

```



## Compare different algorithm vs Louvain
to see which is the algorithm that better fits the network
```{r}
#Infomap
 comp_I <- robinCompare(graph=graph, method1="louvain",
                        method2="infomap", measure="vi", type="independent")
 


#Walktrap
comp_W <- robinCompare(graph=graph, method1="louvain",
                       method2="walktrap", measure="vi", type="independent")




#LabelProp
comp_La <- robinCompare(graph=graph, method1="louvain",
                        method2="labelProp", measure="vi", type="independent",verbose=TRUE)




#LeadingEigen
comp_Le <- robinCompare(graph=graph, method1="louvain",
                        method2="leadingEigen", measure="vi", type="independent",verbose=TRUE)



#Fastgreedy
comp_F <- robinCompare(graph=graph, method1="louvain",
                        method2="fastGreedy", measure="vi", type="independent",verbose=TRUE)


###Plots:
plot1 <- plotRobin(graph=graph, model1=comp_I$Mean1, model2=comp_I$Mean2,
measure="vi", legend=c("louvain","infomap"))


plot2 <- plotRobin(graph=graph, model1=comp_La$Mean1, model2=comp_La$Mean2,
measure="vi", legend=c("louvain","labelProp"))

cols <- c("model1" = "#00BFC4", "model2" = "#F8766D") 
plot3 <- plotRobin(graph=graph, model1=comp_W$Mean1, model2=comp_W$Mean2,
measure="vi")+ggplot2::scale_colour_manual(values = cols,breaks = c("model1", "model2"), labels=c("louvain", "walktrap"))


plot4 <- plotRobin(graph=graph, model1=comp_F$Mean1, model2=comp_F$Mean2,
measure="vi", legend=c("louvain", "fastGreedy"))



plot5 <- plotRobin(graph=graph, model1=comp_Le$Mean1, model2=comp_Le$Mean2,
measure="vi", legend=c("louvain", "LeadingEigen"))


PlotComparisonAllVsInfomap <- gridExtra::grid.arrange(plot1,plot2,plot3,plot4,plot5,ncol=2)


```

## Statistical significance of communities
```{r}
graphRandom <- random(graph=graph)
proc <-robinRobust(graph=graph, graphRandom=graphRandom, method="louvain",
measure="vi",type="independent")

plotRobin(graph=graph, model1=proc$Mean, model2=proc$MeanRandom,
measure="vi", legend=c("real data", "null model"))
```

